let productos = [
    {
      "id": 1,
      "producto": "Te en hebras",
      "precio": 420,
      "descripción": "Naranja Allspice",
      "categoría": "Alimentos",
      "oferta": false,
      "img": "img/naranjaallspice.jpg" ,
    },
    {
        "id": 2,
        "producto": "Golden Milk",
        "precio": 350,
        "descripción": "Leche de curcuma",
        "categoría": "Alimentos",
        "oferta": false,
        "img": "img/goldenmilk.jpg",
    },
    {
        "id": 3,
        "producto": "Te en hebras",
        "precio": 250,
        "descripción": "Manzanilla",
        "categoría": "Alimentos",
        "oferta": false,
        "img": "img/manzanilla.jpg",
    },
    // {
        // "id": 4,
        // "producto": "Te en hebras",
        // "precio": 450,
        // "descripción": "Te Chai",
        // "categoría": "Alimentos",
        // "oferta": false,
        // "img": "",
    // },
    // {
        // "id": 5,
        // "producto": "Te en hebras",
        // "precio": 420,
        // "descripción": "Hibiscus",
        // "categoría": "Alimentos",
        // "oferta": true,
        // "img": "",
    // },
    // {
        // "id": 6,
        // "producto": "Pimenton",
        // "precio": 200,
        // "descripción": "Pimenton Español",
        // "categoría": "Alimentos",
        // "oferta": false,
        // "img": "",
    // },
    // {
        // "id": 7,
        // "producto": "Pimenton",
        // "precio": 200,
        // "descripción": "Pimenton Ahumado Español",
        // "categoría": "Alimentos",
        // "oferta": false,
        // "img": "",
    // },
    // {
        // "id": 8,
        // "producto": "Pimenton",
        // "precio": 200,
        // "descripción": "Pimenton Dulce Español",
        // "categoría": "Alimentos",
        // "oferta": false,
        // "img": "",
    // },
    // {
        // "id": 9,
        // "producto": "Cardamomo",
        // "precio": 350,
        // "descripción": "Semillas de Cardamomo",
        // "categoría": "Alimentos",
        // "oferta": false,
        // "img": "",
    // },
    // {
        // "id": 10,
        // "producto": "Comino",
        // "precio": 150,
        // "descripción": "Semillas de comino",
        // "categoría": "Alimentos",
        // "oferta": false,
        // "img": "",
    // },
    // {
        // "id": 11,
        // "producto": "Curcuma",
        // "precio": 150,
        // "descripción": "Raiz de curcuma",
        // "categoría": "Alimentos",
        // "oferta": false,
        // "img": "",
    // },
    // {
        // "id": 12,
        // "producto": "Baharat",
        // "precio": 350,
        // "descripción": "7 especias Libanesas",
        // "categoría": "Alimentos",
        // "oferta": true,
        // "img": "",
    // },
    // {
        // "id": 13,
        // "producto": "Curry",
        // "precio": 300,
        // "descripción": "Biryani Masala",
        // "categoría": "Alimentos",
        // "oferta": true,
        // "img": "",
    // },
    // {
        // "id": 14,
        // "producto": "Merken",
        // "precio": 250,
        // "descripción": "Condimento mapuche",
        // "categoría": "Alimentos",
        // "oferta": true,
        // "img": "",
    // },
    // {
        // "id": 15,
        // "producto": "Harissa",
        // "precio": 250,
        // "descripción": "Mix de pimientos para salsa picante estilo magrebi",
        // "categoría": "Alimentos",
        // "oferta": true,
        // "img": "",
    // },
]